import { prisma } from "@/lib/prisma";

type AutoLogSource =
  | "photo-equipment"
  | "photo-asset"
  | "map-drawing"
  | "location-ping"
  | "ics"
  | "github";

type EnsureAutoLogInput = {
  userId: string;
  source: AutoLogSource;
  /** Equipment IDs to link/merge. Will be added (de-duped) to the auto entry. */
  equipmentIds?: string[];
  /** JobAsset IDs to link/merge. Will be added (de-duped) to the auto entry. */
  assetIds?: string[];
  /** Optional position to attach if no auto entry exists yet today. */
  positionId?: string | null;
  /** Date the activity happened on (defaults to today). */
  date?: Date;
  /**
   * External event reference (Phase B integrations). When provided we look up by
   * (userId, externalSource, externalId) first and update that exact row, falling
   * back to today's merge behavior. Required for calendar/GitHub sync to be
   * idempotent across re-runs.
   */
  externalRef?: { source: "ics" | "github" | "google-calendar" | "microsoft-graph"; id: string };
  /** Optional title override (e.g. calendar event summary, PR title). */
  title?: string;
  /** Optional content override (e.g. event description, commit messages). */
  content?: string;
  /** Optional duration in hours (e.g. calendar event length). */
  hours?: number;
};

const SOURCE_TITLES: Record<AutoLogSource, string> = {
  "photo-equipment": "Tool activity (auto)",
  "photo-asset": "Asset activity (auto)",
  "map-drawing": "Site activity (auto)",
  "location-ping": "Location ping (auto)",
  "ics": "Calendar activity (auto)",
  "github": "Coding activity (auto)",
};

/**
 * Find or create the auto-generated WorkLog entry for the user on the given day,
 * then merge the provided equipment / asset IDs into its arrays.
 *
 * Rules (Phase B implicit logging):
 *  - One auto entry per user per day. If one already exists (isAutoGenerated=true),
 *    we merge into it instead of creating duplicates.
 *  - We never overwrite a user-authored entry (isAutoGenerated=false).
 *  - We never touch entries the user has already promoted to a CareerEvent.
 *  - Manual edits the user makes to the auto row stay intact (we only union the ID arrays).
 *  - When an externalRef is provided we treat that event as the unit of dedupe, so
 *    re-syncing the same calendar feed updates the row in place instead of stacking.
 */
export async function ensureAutoLog(input: EnsureAutoLogInput) {
  const date = input.date ?? new Date();
  const start = new Date(date);
  start.setHours(0, 0, 0, 0);
  const end = new Date(start);
  end.setDate(end.getDate() + 1);

  const newEquipment = input.equipmentIds ?? [];
  const newAssets = input.assetIds ?? [];

  // Path A — external event with stable id: look up by composite unique.
  if (input.externalRef) {
    const existing = await prisma.workLog.findFirst({
      where: {
        userId: input.userId,
        externalSource: input.externalRef.source,
        externalId: input.externalRef.id,
      },
    });
    if (existing) {
      // Don't clobber user edits to the title/content if they've taken ownership of it.
      const stillUnedited = existing.isAutoGenerated && !existing.promotedToCareerEventId;
      return prisma.workLog.update({
        where: { id: existing.id },
        data: {
          equipmentIds: Array.from(new Set([...(existing.equipmentIds ?? []), ...newEquipment])),
          assetIds: Array.from(new Set([...(existing.assetIds ?? []), ...newAssets])),
          positionId: existing.positionId ?? input.positionId ?? null,
          ...(stillUnedited && input.title ? { title: input.title } : {}),
          ...(stillUnedited && input.content !== undefined ? { content: input.content } : {}),
          ...(stillUnedited && input.hours !== undefined ? { hours: input.hours } : {}),
        },
      });
    }
    return prisma.workLog.create({
      data: {
        userId: input.userId,
        date: input.date ?? start,
        title: input.title ?? SOURCE_TITLES[input.source],
        content: input.content ?? null,
        hours: input.hours ?? null,
        category: "task",
        isAutoGenerated: true,
        equipmentIds: newEquipment,
        assetIds: newAssets,
        positionId: input.positionId ?? null,
        visibility: "PRIVATE",
        externalSource: input.externalRef.source,
        externalId: input.externalRef.id,
      },
    });
  }

  // Path B — no external id: merge into today's auto row (legacy behavior).
  const existing = await prisma.workLog.findFirst({
    where: {
      userId: input.userId,
      isAutoGenerated: true,
      externalId: null,
      date: { gte: start, lt: end },
    },
    orderBy: { createdAt: "asc" },
  });

  if (existing) {
    return prisma.workLog.update({
      where: { id: existing.id },
      data: {
        equipmentIds: Array.from(new Set([...(existing.equipmentIds ?? []), ...newEquipment])),
        assetIds: Array.from(new Set([...(existing.assetIds ?? []), ...newAssets])),
        positionId: existing.positionId ?? input.positionId ?? null,
      },
    });
  }

  return prisma.workLog.create({
    data: {
      userId: input.userId,
      date: start,
      title: SOURCE_TITLES[input.source],
      category: "task",
      isAutoGenerated: true,
      equipmentIds: newEquipment,
      assetIds: newAssets,
      positionId: input.positionId ?? null,
      visibility: "PRIVATE",
    },
  });
}
