-- AlterTable
ALTER TABLE "WorkHistory" ADD COLUMN     "accomplishments" TEXT,
ADD COLUMN     "benefits" TEXT,
ADD COLUMN     "bonusAmount" DOUBLE PRECISION,
ADD COLUMN     "commuteDistance" DOUBLE PRECISION,
ADD COLUMN     "commuteMinutes" INTEGER,
ADD COLUMN     "commuteMode" TEXT,
ADD COLUMN     "companySize" TEXT,
ADD COLUMN     "department" TEXT,
ADD COLUMN     "equityNotes" TEXT,
ADD COLUMN     "hoursPerWeek" DOUBLE PRECISION,
ADD COLUMN     "hybridDays" INTEGER,
ADD COLUMN     "managerName" TEXT,
ADD COLUMN     "promotions" TEXT,
ADD COLUMN     "ptoDaysOffered" INTEGER,
ADD COLUMN     "ptoDaysUsed" INTEGER,
ADD COLUMN     "ptoNotes" TEXT,
ADD COLUMN     "reasonForLeaving" TEXT,
ADD COLUMN     "salaryAmount" DOUBLE PRECISION,
ADD COLUMN     "salaryCurrency" TEXT DEFAULT 'USD',
ADD COLUMN     "salaryType" TEXT,
ADD COLUMN     "scheduleType" TEXT,
ADD COLUMN     "shiftNotes" TEXT,
ADD COLUMN     "skillsGained" TEXT,
ADD COLUMN     "skillsUsed" TEXT,
ADD COLUMN     "teamSize" INTEGER,
ADD COLUMN     "workMode" TEXT,
ADD COLUMN     "wouldReturn" TEXT;
