/**
 * Worklog-domain types shared across:
 *   - src/components/worklog/worklog-page.tsx (full editor)
 *   - src/components/quick-log-dialog.tsx (lightweight Quick Log)
 *   - src/components/equipment-picker.tsx
 *   - src/components/asset-picker.tsx
 *
 * Pure type module — no runtime exports — so it can be imported anywhere
 * without bundle cost.
 */

// Re-export picker types/constants so consumers have a single import surface
// when they need everything worklog-shaped.
export type { EquipmentItem } from "@/components/equipment-picker";
export type { JobAsset } from "@/components/asset-picker";

export type WorkLogPhoto = {
  id: string;
  filePath: string;
  caption: string | null;
};

export type WorkLog = {
  id: string;
  userId: string;
  positionId: string | null;
  shiftId: string | null;
  date: string;
  workdayDate: string | null;
  title: string;
  content: string | null;
  /** ProseMirror JSON source of truth (Tiptap editor). May be null for legacy notes. */
  contentJson?: unknown | null;
  category: string;
  hours: number | null;
  tags: string | null;
  accomplishment: boolean;
  impact: string | null;
  isNotable: boolean;
  mood: string | null;
  templateId: string | null;
  isAutoGenerated: boolean;
  equipmentIds: string[];
  assetIds: string[];
  promotedToCareerEventId: string | null;
  visibility: string;
  createdAt: string;
  updatedAt: string;
  photos?: WorkLogPhoto[];
  shift?: WorkShift | null;
};

export type WorkShift = {
  id: string;
  userId: string;
  workHistoryId: string;
  name: string;
  startMinute: number;
  endMinute: number;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
};

export type WorklogPreferences = {
  defaultPositionId: string | null;
  defaultShiftId: string | null;
  defaultCategory: string;
  defaultMood: string | null;
  defaultHours: number | null;
};

export type Template = {
  id: string;
  userId: string;
  name: string;
  description: string | null;
  icon: string | null;
  color: string | null;
  defaultPositionId: string | null;
  defaultCategory: string;
  defaultTitle: string | null;
  defaultTags: string | null;
  defaultEquipmentIds: string[];
  defaultAssetIds: string[];
  defaultMood: string | null;
  defaultDurationMinutes: number | null;
  sortOrder: number;
  useCount: number;
  lastUsedAt: string | null;
};

/**
 * CareerEvent type for events with geocoded location
 */
export type CareerEvent = {
  id: string;
  workHistoryId: string;
  title: string;
  description: string | null;
  date: string; // ISO string
  location: string;
  lat: number | null;
  lng: number | null;
  photos?: WorkLogPhoto[];
  createdAt: string;
  updatedAt: string;
};

export type Position = {
  id: string;
  company: string;
  title: string | null;
  endDate: string | null;
  type: string;
};
