-- Item #19 Phase A: extend WorkLog into a daily-ritual model + add WorkLogTemplate

-- 1. Add new columns to WorkLog (userId nullable for backfill)
ALTER TABLE "WorkLog" ADD COLUMN "userId" TEXT;
ALTER TABLE "WorkLog" ADD COLUMN "isNotable" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "WorkLog" ADD COLUMN "mood" TEXT;
ALTER TABLE "WorkLog" ADD COLUMN "templateId" TEXT;
ALTER TABLE "WorkLog" ADD COLUMN "isAutoGenerated" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "WorkLog" ADD COLUMN "equipmentIds" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "WorkLog" ADD COLUMN "promotedToCareerEventId" TEXT;
ALTER TABLE "WorkLog" ADD COLUMN "visibility" TEXT NOT NULL DEFAULT 'PRIVATE';

-- 2. Backfill userId from the linked WorkHistory position
UPDATE "WorkLog"
SET "userId" = wh."userId"
FROM "WorkHistory" wh
WHERE "WorkLog"."positionId" = wh."id" AND "WorkLog"."userId" IS NULL;

-- 3. Make userId required, positionId optional (allow standalone "general day" logs)
ALTER TABLE "WorkLog" ALTER COLUMN "userId" SET NOT NULL;
ALTER TABLE "WorkLog" ALTER COLUMN "positionId" DROP NOT NULL;

-- 4. Drop the old required FK on positionId and re-add as nullable
ALTER TABLE "WorkLog" DROP CONSTRAINT IF EXISTS "WorkLog_positionId_fkey";
ALTER TABLE "WorkLog"
  ADD CONSTRAINT "WorkLog_positionId_fkey"
  FOREIGN KEY ("positionId") REFERENCES "WorkHistory"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- 5. Add FK on userId
ALTER TABLE "WorkLog"
  ADD CONSTRAINT "WorkLog_userId_fkey"
  FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- 6. Indexes
CREATE INDEX "WorkLog_userId_date_idx" ON "WorkLog"("userId", "date");
CREATE INDEX "WorkLog_positionId_idx" ON "WorkLog"("positionId");
CREATE INDEX "WorkLog_templateId_idx" ON "WorkLog"("templateId");

-- 7. New table WorkLogTemplate
CREATE TABLE "WorkLogTemplate" (
  "id"                     TEXT NOT NULL,
  "userId"                 TEXT NOT NULL,
  "name"                   TEXT NOT NULL,
  "description"            TEXT,
  "icon"                   TEXT,
  "color"                  TEXT,
  "defaultPositionId"      TEXT,
  "defaultCategory"        TEXT NOT NULL DEFAULT 'task',
  "defaultTitle"           TEXT,
  "defaultTags"            TEXT,
  "defaultEquipmentIds"    TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  "defaultMood"            TEXT,
  "defaultDurationMinutes" INTEGER,
  "sortOrder"              INTEGER NOT NULL DEFAULT 0,
  "useCount"               INTEGER NOT NULL DEFAULT 0,
  "lastUsedAt"             TIMESTAMP(3),
  "createdAt"              TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt"              TIMESTAMP(3) NOT NULL,
  CONSTRAINT "WorkLogTemplate_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "WorkLogTemplate_userId_idx" ON "WorkLogTemplate"("userId");
CREATE INDEX "WorkLogTemplate_defaultPositionId_idx" ON "WorkLogTemplate"("defaultPositionId");

ALTER TABLE "WorkLogTemplate"
  ADD CONSTRAINT "WorkLogTemplate_userId_fkey"
  FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "WorkLogTemplate"
  ADD CONSTRAINT "WorkLogTemplate_defaultPositionId_fkey"
  FOREIGN KEY ("defaultPositionId") REFERENCES "WorkHistory"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- 8. WorkLog.templateId FK
ALTER TABLE "WorkLog"
  ADD CONSTRAINT "WorkLog_templateId_fkey"
  FOREIGN KEY ("templateId") REFERENCES "WorkLogTemplate"("id") ON DELETE SET NULL ON UPDATE CASCADE;
