-- AlterTable
ALTER TABLE "PersonalEquipmentPhoto" ADD COLUMN     "focalX" INTEGER NOT NULL DEFAULT 50,
ADD COLUMN     "focalY" INTEGER NOT NULL DEFAULT 50,
ADD COLUMN     "zoom" DOUBLE PRECISION NOT NULL DEFAULT 1;
