/**
 * useWorklogFilters — owns the 5 filter selectors, derives the filtered list,
 * groups it by day, and produces the timeline segments (including routine-day
 * rollups for runs of 3+ standard same-position days).
 */

import { useMemo, useState } from "react";
import { format, parseISO, startOfDay, differenceInCalendarDays } from "date-fns";
import type { WorkLog } from "@/types/worklog";

export type TimelineSegment =
  | { kind: "day"; date: Date; logs: WorkLog[] }
  | {
      kind: "rollup";
      positionId: string;
      start: Date;
      end: Date;
      days: { date: Date; logs: WorkLog[] }[];
      totalHours: number;
    };

/**
 * A day qualifies as "routine" (rollup-eligible) when ALL of:
 *  • 1–2 entries
 *  • all entries share the same non-null positionId
 *  • no notable/accomplishment flags
 *  • no photos
 *  • not auto-generated (so user can review them)
 *
 * Returns the positionId on match, or null otherwise.
 */
function isRoutineDay(logs: WorkLog[]): string | null {
  if (!logs.length || logs.length > 2) return null;
  const pos = logs[0].positionId;
  if (!pos) return null;
  for (const l of logs) {
    if (l.positionId !== pos) return null;
    if (l.isNotable || l.accomplishment) return null;
    if (l.photos && l.photos.length > 0) return null;
    if (l.isAutoGenerated) return null;
  }
  return pos;
}

export function useWorklogFilters(logs: WorkLog[]) {
  const [filterPositionId, setFilterPositionId] = useState<string>("all");
  const [filterCategory, setFilterCategory] = useState<string>("all");
  const [filterNotable, setFilterNotable] = useState(false);
  const [filterEquipmentId, setFilterEquipmentId] = useState<string>("all");
  const [filterAssetId, setFilterAssetId] = useState<string>("all");

  const filteredLogs = useMemo(() => {
    return logs.filter((l) => {
      if (filterPositionId !== "all") {
        if (filterPositionId === "none" && l.positionId) return false;
        if (filterPositionId !== "none" && l.positionId !== filterPositionId) return false;
      }
      if (filterCategory !== "all" && l.category !== filterCategory) return false;
      if (filterNotable && !l.isNotable && !l.accomplishment) return false;
      if (filterEquipmentId !== "all" && !(l.equipmentIds ?? []).includes(filterEquipmentId)) return false;
      if (filterAssetId !== "all" && !(l.assetIds ?? []).includes(filterAssetId)) return false;
      return true;
    });
  }, [logs, filterPositionId, filterCategory, filterNotable, filterEquipmentId, filterAssetId]);

  const grouped = useMemo(() => {
    const map = new Map<string, WorkLog[]>();
    for (const l of filteredLogs) {
      const key = format(startOfDay(parseISO(l.date)), "yyyy-MM-dd");
      if (!map.has(key)) map.set(key, []);
      map.get(key)!.push(l);
    }
    return Array.from(map.entries())
      .sort((a, b) => (a[0] < b[0] ? 1 : -1))
      .map(([k, v]) => ({ date: parseISO(k), logs: v }));
  }, [filteredLogs]);

  const timeline = useMemo<TimelineSegment[]>(() => {
    const out: TimelineSegment[] = [];
    let i = 0;
    while (i < grouped.length) {
      const cur = grouped[i];
      const pos = isRoutineDay(cur.logs);
      if (!pos) {
        out.push({ kind: "day", ...cur });
        i++;
        continue;
      }
      // Walk forward (descending date) collecting consecutive same-position routine days.
      const run: { date: Date; logs: WorkLog[] }[] = [cur];
      let j = i + 1;
      while (j < grouped.length) {
        const nxt = grouped[j];
        const nPos = isRoutineDay(nxt.logs);
        if (nPos !== pos) break;
        if (differenceInCalendarDays(run[run.length - 1].date, nxt.date) !== 1) break;
        run.push(nxt);
        j++;
      }
      if (run.length >= 3) {
        const totalHours = run.reduce(
          (s, d) => s + d.logs.reduce((ss, l) => ss + (l.hours ?? 0), 0),
          0,
        );
        out.push({
          kind: "rollup",
          positionId: pos,
          start: run[run.length - 1].date,
          end: run[0].date,
          days: run,
          totalHours,
        });
        i = j;
      } else {
        out.push({ kind: "day", ...cur });
        i++;
      }
    }
    return out;
  }, [grouped]);

  const isAnyFilterActive =
    filterPositionId !== "all" ||
    filterCategory !== "all" ||
    filterNotable ||
    filterEquipmentId !== "all" ||
    filterAssetId !== "all";

  function clearAll() {
    setFilterPositionId("all");
    setFilterCategory("all");
    setFilterNotable(false);
    setFilterEquipmentId("all");
    setFilterAssetId("all");
  }

  return {
    // state + setters
    filterPositionId,
    setFilterPositionId,
    filterCategory,
    setFilterCategory,
    filterNotable,
    setFilterNotable,
    filterEquipmentId,
    setFilterEquipmentId,
    filterAssetId,
    setFilterAssetId,
    // derived
    filteredLogs,
    grouped,
    timeline,
    isAnyFilterActive,
    // actions
    clearAll,
  };
}
